version: '3'
services:
  web:
    build: './'
    container_name: SAML_web
    volumes:
      - ./:/var/www/html/
    ports:
      - "8000:80"
      - "443:443"
    stdin_open: true
    tty: true
    